#!/bin/bash
# Script to generate embedded assets header file

OUTPUT_FILE="src/embedded_assets.h"

echo "// Auto-generated file - do not edit manually" > "$OUTPUT_FILE"
echo "// Generated by embed_assets.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "#pragma once" >> "$OUTPUT_FILE"
echo "#include <stddef.h>" >> "$OUTPUT_FILE"
echo "#include <string.h>" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Find all asset files
ASSETS=$(find src -type f \( -name "*.bmp" -o -name "*.wav" -o -name "*.ttf" -o -name "*.dat" \) | sort)

# Generate array for each asset
for file in $ASSETS; do
    # Create a valid C identifier from the path
    varname=$(echo "$file" | sed 's/[^a-zA-Z0-9]/_/g')

    echo "// $file" >> "$OUTPUT_FILE"
    echo "static const unsigned char ${varname}[] = {" >> "$OUTPUT_FILE"
    xxd -i < "$file" >> "$OUTPUT_FILE"
    echo "};" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

# Generate lookup structure
echo "// Asset lookup structure" >> "$OUTPUT_FILE"
echo "typedef struct {" >> "$OUTPUT_FILE"
echo "    const char *path;" >> "$OUTPUT_FILE"
echo "    const unsigned char *data;" >> "$OUTPUT_FILE"
echo "    size_t size;" >> "$OUTPUT_FILE"
echo "} EmbeddedAsset;" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "static const EmbeddedAsset embedded_assets[] = {" >> "$OUTPUT_FILE"
for file in $ASSETS; do
    varname=$(echo "$file" | sed 's/[^a-zA-Z0-9]/_/g')
    echo "    { \"$file\", ${varname}, sizeof(${varname}) }," >> "$OUTPUT_FILE"
done
echo "    { NULL, NULL, 0 }" >> "$OUTPUT_FILE"
echo "};" >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "static inline const EmbeddedAsset* findEmbeddedAsset(const char *path) {" >> "$OUTPUT_FILE"
echo "    for (int i = 0; embedded_assets[i].path != NULL; i++) {" >> "$OUTPUT_FILE"
echo "        if (strcmp(embedded_assets[i].path, path) == 0) {" >> "$OUTPUT_FILE"
echo "            return &embedded_assets[i];" >> "$OUTPUT_FILE"
echo "        }" >> "$OUTPUT_FILE"
echo "    }" >> "$OUTPUT_FILE"
echo "    return NULL;" >> "$OUTPUT_FILE"
echo "}" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE with $(echo "$ASSETS" | wc -w | tr -d ' ') assets"
