#pragma once

#include "bricks/brick.h"

#define LEVEL_PATTERN_COLS 15
#define LEVEL_PATTERN_ROWS 150
#define LEVEL_PATTERN_LENGTH (LEVEL_PATTERN_COLS * LEVEL_PATTERN_ROWS)
#define LEVEL_PATTERN_INDENT 11
#define LEVEL_PATTERN_SPACING 2
#define LEVEL_PATTERN_ROW_HEIGHT 20
#define LEVEL_HEIGHT (LEVEL_PATTERN_INDENT + LEVEL_PATTERN_ROWS * (LEVEL_PATTERN_ROW_HEIGHT + LEVEL_PATTERN_SPACING))

typedef struct Level
{
  BrickType pattern[LEVEL_PATTERN_LENGTH];
} Level;
